#!/usr/bin/env bash
# NEXUS per-node service assignment for 5-node cluster (1 master + 4 workers)
# Generated by startup scripts. Each VM runs only its assigned services.
#
# Architecture:
#   Master (VM 1):          Coordination + UI + 1 distributed node each
#   Worker 1 (VM 2):        ZK-2, Kafka-2, MinIO-2 + compute + api
#   Worker 2 (VM 3):        ZK-3, Kafka-3, MinIO-3 + compute + api
#   Worker 3 (VM 4):        MinIO-4 + compute + gov-db-replica
#   Worker 4 (VM 5):        Pure compute

master_services() {
  echo "zookeeper-1 kafka-1 minio-1 minio-init \
    hive-metastore-db hive-metastore \
    airflow-db governance-db-primary \
    redis spark spark-worker-1 \
    trino-coordinator trino-worker-1 \
    airflow airflow-scheduler-1 airflow-scheduler-2 airflow-worker-1 airflow-worker-2 \
    superset api-lb api-1"
}

worker1_services() {
  echo "zookeeper-2 kafka-2 minio-2 spark-worker trino-worker airflow-worker api-2"
}

worker2_services() {
  echo "zookeeper-3 kafka-3 minio-3 spark-worker trino-worker airflow-worker api-3"
}

worker3_services() {
  echo "minio-4 spark-worker trino-worker airflow-worker governance-db-replica"
}

worker4_services() {
  echo "spark-worker trino-worker airflow-worker"
}

node_services() {
  if [ "${NEXUS_NODE_ROLE}" = "master" ]; then
    master_services
  elif [ "${NEXUS_NODE_ROLE}" = "worker" ]; then
    case "${NEXUS_NODE_INDEX:-1}" in
      1) worker1_services ;;
      2) worker2_services ;;
      3) worker3_services ;;
      4) worker4_services ;;
      *) echo "" ;;
    esac
  fi
}
