# Data Caterer integration package for NEXUS — TPC-DI SF=3/10/50
from ingestion.data_caterer.runner import (
    DataCatererConfig,
    generate_tpcdi,
    generate_all,
    list_plans,
    run_plan,
    ERROR_PRESETS,
    EXPORT_FORMATS,
)
from ingestion.data_caterer.error_injector import (
    ErrorConfig,
    apply_error_profile,
    inject_nulls,
    inject_duplicates,
    inject_fk_violations,
    inject_schema_drift,
    inject_format_errors,
    inject_type_errors,
    inject_out_of_order,
)
from ingestion.data_caterer.generators import (
    get_generator,
    random_amount,
    random_date,
    random_discount,
    random_phone,
    random_quantity,
    random_tax,
    tpcdi_sp_rating,
    tpcdi_status,
    tpcdi_issue_type,
)

__all__ = [
    "DataCatererConfig",
    "ErrorConfig",
    "ERROR_PRESETS",
    "EXPORT_FORMATS",
    "apply_error_profile",
    "generate_all",
    "generate_tpcdi",
    "get_generator",
    "inject_duplicates",
    "inject_fk_violations",
    "inject_format_errors",
    "inject_nulls",
    "inject_out_of_order",
    "inject_schema_drift",
    "inject_type_errors",
    "list_plans",
    "random_amount",
    "random_date",
    "random_discount",
    "random_phone",
    "random_quantity",
    "random_tax",
    "run_plan",
    "tpcdi_issue_type",
    "tpcdi_sp_rating",
    "tpcdi_status",
]
