name: nexus_dbt
version: 0.1.0
config-version: 2

profile: nexus

model-paths:
  - models
seed-paths:
  - seeds

models:
  nexus_dbt:
    gold:
      +materialized: table
      +schema: gold

seeds:
  nexus_dbt:
    +schema: reference
    +quote_columns: false
